<?php

/**
 * This file is part of the Flaphl package.
 *
 * (c) Jade Phyressi <jade@flaphl.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Flaphl\Fridge\Precept\Id;

/**
 * Identity generator for auto-increment IDs.
 * The ID is generated by the database after INSERT.
 */
class IdentityGenerator extends AbstractIdGenerator
{
    public function generate(object $entity): mixed
    {
        // Identity generators don't generate IDs - the database does
        return null;
    }

    public function isPostInsertGenerator(): bool
    {
        // Database generates ID after insert
        return true;
    }

    public function getName(): string
    {
        return 'identity';
    }

    /**
     * Retrieve the last inserted ID from the database.
     */
    public function getLastInsertId(?string $sequenceName = null): string|int
    {
        return $this->connection->lastInsertId($sequenceName);
    }
}
